                        <?php
return [
    "1" => [ // Platform Facebook
        'audience_info' => [
            'uid' => 'audience_info',
            'name' => 'Audience',
            'chart_type' => 'card',
            'callback' => '',
            'cols' => 3.3,
            'rows' => 7
        ],
        'behavior_info' => [
            'uid' => 'behavior_info',
            'name' => 'Behavior',
            'chart_type' => 'card',
            'callback' => '',
            'cols' => 3.3,
            'rows' => 7
        ],
        'media_info' => [
            'uid' => 'media_info',
            'name' => 'Media',
            'chart_type' => 'card',
            'callback' => '',
            'cols' => 3.3,
            'rows' => 7
        ],
        'new_fans' => [
            'uid'=>'new_fans',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_variation&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,

        ],
        'page_likes_count_progression' => [
            'uid'=>'page_likes_count_progression',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_variation&chart_type=raw',
            'cols' => 6,
            'rows' => 3,
        ],
        'fan_number' => [
            'uid' => 'fan_number',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fan_count&return=summary|lastNonNull',
            'help' => 'this is to display a help on the widget',
            'cols' => 2,
            'rows' => 2,
            'options' => []
        ],
        'interactions_total' => [
            'uid'=>'interactions_total',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_interactions&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'reactions_total' => [
            'uid'=>'reactions_total',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_reactions&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'shares_total' => [
            'uid'=>'shares_total',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_shares&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'average_page_engagement' => [
            'uid'=>'average_page_engagement', 
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_engagement_rate&return=account|avg&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'interactions_by_type' => [
            'uid' => 'interactions_by_type',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_shares,kpeiz_account_total_comments,kpeiz_account_total_reactions&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'cols' => 2,
            'rows' => 2,
        ],
        'page_posts' => [
            'uid' => 'page_posts',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_date&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'fans_posts_count' => [
            'uid' => 'fans_posts_count',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_posts_count&return=summary|sum&chart_type=number',
            'cols' => 2,
            'rows' => 2,
        ],
        'kpeiz_post_count_by_type' => [
            'uid'=>'kpeiz_post_count_by_type',
            'chart_type'=>'pie',
            'data_source'=>'data/account/{ids}?fields=kpeiz_post_count_by_type&chart_type=raw&return=summary|sum',
            'cols' => 4,
            'rows' => 4,
        ],
        'average_page_engagement' => [
            'uid' => 'average_page_engagement',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_engagement_rate&return=account|avg&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'page_posts' => [
            'uid' => 'page_posts',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_date&return=summary|sum&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'engaged_users' => [
            'uid' => 'engaged_users',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=page_engaged_users&return=summary|sum&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'avg_post_engagement' => [
            'uid' => 'avg_post_engagement',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_avg_posts_engagement_rate&return=account|avg&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],'cols' => 2,
            'rows' => 2,
        ],
         'avg_posts_engagement_rate' => [
            'uid' => 'avg_posts_engagement_rate',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_avg_posts_engagement_rate&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'new_fans' => [
            'uid' => 'new_fans',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_variation&return=summary|sum&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'worldmap' => [
            'uid' => 'worldmap',
            'chart_type' => 'map',
            'data_source' => 'data/account/{ids}?fields=page_fans_country&return=summary|max',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'impressions' => [
            'uid' => 'impressions',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=page_impressions&groupBy=object&return=summary|sum&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'reactions' => [
            'uid' => 'reactions',
            'chart_type' => 'reactions',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_reactions_by_type&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'fans_posts_count' => [
            'uid' => 'fans_posts_count',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_posts_count&return=summary|sum&chart_type=number',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'page_posts_bar' => [
            'uid' => 'page_posts_bar',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_date&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'engagement_rate_variation' => [
            'uid' => 'engagement_rate_variation',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_engagement_rate&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'interactions_by_type' => [
            'uid' => 'interactions_by_type',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_shares,kpeiz_account_total_comments,kpeiz_account_total_reactions&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'gender_age' => [
            'uid' => 'gender_age',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=page_fans_gender_age&chart_type=bar',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'fans_online' => [
            'uid' => 'fans_online',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=page_fans_online_per_day&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'page_likes_count_progression' => [
            'uid' => 'page_likes_count_progression',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_variation&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'fans_region' => [
            'uid' => 'fans_region',
            'chart_type' => 'table',
            'data_source' => 'data/account/{ids}?fields=page_fans_city&return=summary|max',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'page_posts_by_type' => [
            'uid' => 'page_posts_by_type',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_type&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'fan_posts_by_type' => [
            'uid' => 'fan_posts_by_type',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fan_post_count_by_type&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'posts_by_day' => [
            'uid' => 'posts_by_day',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_date&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'posts_by_hour' => [
            'uid' => 'posts_by_hour',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_hour&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'reactions_progression' => [
            'uid' => 'reactions_progression',
            'chart_type' => 'line',
            //'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_reactions_by_type&chart_type=raw&return=summary|sum',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_reactions_by_type&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'online_fans_per_hour' => [
            'uid' => 'online_fans_per_hour',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=page_fans_online&chart_type=raw&return=summary|max',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'negative_feedback' => [
            'uid' => 'negative_feedback',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=page_negative_feedback&chart_type=raw&return=summary|lastNonNull',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'engagement_on_reach' => [
            'uid' => 'engagement_on_reach',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_engagement_on_reach&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'avg_engagement_on_reach' => [
            'uid' => 'avg_engagement_on_reach',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=Average%20engagement:(%7Bavg%7Cpage_positive_feedback_by_type%7D[plus]%7Bsum%7Cpage_actions_post_reactions_total%7D)/%7Bpage_impressions_unique%7D&groupBy=object',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'implication' => [
            'uid' => 'implication',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_implication&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'fans_posts_count_evolution' => [
            'uid' => 'fans_posts_count_evolution',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fans_posts_count&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'page_fans' => [
            'uid' => 'page_fans',
            'chart_type' => 'heatmap',
            'data_source' => 'data/account/{ids}?fields=page_fans_online&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'impressions_total' => [
            'uid' => 'impressions_total',
            'chart_type' => 'numbers',
            'data_source' => 'data/account/{ids}?fields=page_impressions[sum],page_impressions_paid[sum],page_impressions_organic[sum]&chart_type=number&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 2,
        ],
        'reach_total' => [
            'uid' => 'reach_total',
            'chart_type' => 'numbers',
            'data_source' => 'data/account/{ids}?fields=page_impressions_unique[sum],page_impressions_paid_unique[sum],page_impressions_organic_unique[sum]&chart_type=number&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 2,
        ],
        'total_reach' => [
            'uid' => 'total_reach',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=page_impressions_unique[sum]&chart_type=number&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'total_comments' => [
            'uid' => 'total_comments',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_comments&chart_type=number&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'total_impressions' => [
            'uid' => 'total_impressions',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=page_impressions[sum]&chart_type=number&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 2,
            'rows' => 2,
        ],
        'virality_rate' => [
            'uid' => 'virality_rate',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=virality:{page_content_activity}*100/{page_impressions_unique}&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'all_interactions' => [
            'uid' => 'all_interactions',
            'chart_type' => 'pie',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_shares[sum],kpeiz_account_total_comments[sum],kpeiz_account_total_reactions[sum]&chart_type=raw&since=2019-1-14&until=2019-1-28&return=account',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 4,
            'rows' => 4,
        ],
        'interactions_by_day' => [
            'uid' => 'interactions_by_day',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_interactions&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
            'post_dialog' => true
        ],
        'fans_progression' => [
            'uid' => 'fans_progression',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fan_count&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'cols' => 6,
            'rows' => 3,
            'options' => [
                /*'avg'*/
            ]
        ],
        'avg_rate_of_reached_users' => [
            'uid' => 'avg_rate_of_reached_users',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=Reached%20users:{page_engaged_users}/{page_impressions_unique}*1000',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'paid_and_organic_reach' => [
            'uid' => 'paid_and_organic_reach',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=page_impressions_paid_unique,page_impressions_organic_unique&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'paid_and_organic_impressions' => [
            'uid' => 'paid_and_organic_impressions',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=page_impressions_paid,page_impressions_organic&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'page_impressions' => [
            'uid' => 'page_impressions',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=page_impressions&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'interactions_number' => [
            'uid' => 'interactions_number',
            'chart_type' => 'interactions',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_interactions[sum],kpeiz_account_total_reactions[sum],kpeiz_account_total_comments[sum],kpeiz_account_total_shares[sum]&return=account&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'reactions_pie' => [
            'uid' => 'reactions_pie',
            'chart_type' => 'pie',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_reactions_by_type&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 4,
            'rows' => 4,
        ],
        'gender_pie' => [
            'uid' => 'gender_pie',
            'chart_type' => 'pie',
            'data_source' => 'data/account/{ids}?fields=page_fans_gender_age&chart_type=pie',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 4,
            'rows' => 4,
        ],
        'interactions_by_post_type' => [
            'uid' => 'interactions_by_post_type',
            'chart_type' => 'pie',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_interactions_by_post_type&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 4,
            'rows' => 4,
        ],
        'interactions_by_hour' => [
            'uid' => 'interactions_by_hour',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=kpeiz_interactions_by_hour&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
            'post_dialog' => true
        ],
        'fans_by_country' => [
            'uid' => 'fans_by_country',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=page_fans_country&chart_type=raw&return=summary|max&sortByValue&limit=5',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
        'posts' => [
            'uid' => 'posts',
            'chart_type' => 'post',
            'data_source' => 'data/account/{ids}/posts?chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'kpeiz_most_engaging_media' => [
            'uid' => 'kpeiz_most_engaging_media',
            'chart_type' => 'post',
            'data_source' => 'data/account/{ids}/posts?chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'interactions_progress' => [
            'uid' => 'interactions_progress',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_total_interactions&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => [],
            'cols' => 6,
            'rows' => 3,
        ],
    ],
    "2" => [ // Platform Instagram
        'followers_count'=> [
            'uid' => 'followers_count',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fan_count&return=summary|lastNonNull&force_until',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'follower_growth'=> [
            'uid' => 'follower_growth',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_fan_count&chart_type=raw',
        ],
        'follower_count'=> [
            'uid' => 'follower_count',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=follower_count',
        ],
        'audience_gender_age'=> [
            'uid' => 'audience_gender_age',
            'chart_type' => 'bar',
            'data_source' => 'data/account/{ids}?fields=audience_gender_age&chart_type=raw&return=summary|max&force_until',
        ],
        'audience_country'=> [
            'uid' => 'audience_country',
            'chart_type' => 'map',
            'data_source' => 'data/account/{ids}?fields=audience_country&return=summary|max&force_until',
        ],
        'kpeiz_total_posts'=> [
            'uid' => 'kpeiz_total_posts',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=kpeiz_post_count_by_date&return=summary|sum',
        ],
        'audience_city'=> [
            'uid' => 'audience_city',
            'chart_type' => 'table',
            'data_source' => 'data/account/{ids}?fields=audience_city&return=summary|max&force_until',
        ],
        'impressions'=> [
            'uid' => 'impressions',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=impressions&groupBy=object&return=summary|sum&chart_type=number',
        ],
        'reach'=> [
            'uid' => 'reach',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=reach&groupBy=object&return=summary|sum&chart_type=number',
        ],
        'posts' => [
            'uid' => 'posts',
            'chart_type' => 'post',
            'data_source' => 'data/account/{ids}/posts?chart_type=raw',
        ],
        'profile_views'=> [
            'uid' => 'profile_views',
            'chart_type' => 'number',
            'data_source' => 'data/account/{ids}?fields=profile_views',
        ],
        'profile_visit_growth'=> [
            'uid' => 'profile_visit_growth',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=profile_views&chart_type=raw',
        ],
        'total_likes'=>[
             'uid'=>'total_likes',
             'chart_type'=>'number',
             'data_source'=>'data/account/{ids}?fields=kpeiz_account_total_likes&return=summary|sum&chart_type=number',
             'help' => 'this is to display a help on the widget',
             'options' => []
        ],
        'total_comments'=>[
             'uid'=>'total_comments',
             'chart_type'=>'number',
             'data_source'=>'data/account/{ids}?fields=kpeiz_account_total_comments&return=summary|sum&chart_type=number',
             'help' => 'this is to display a help on the widget',
             'options' => []
        ],
        'kpeiz_follower_variation'=>[
             'uid'=>'kpeiz_follower_variation',
             'chart_type'=>'number',
             'data_source'=>'data/account/{ids}?fields=kpeiz_follower_variation&return=summary|sum&chart_type=number',
             'help' => 'this is to display a help on the widget',
             'options' => []
        ],
        'kpeiz_post_count_by_type'=>[
            'uid'=>'kpeiz_post_count_by_type',
            'chart_type'=>'pie',
            'data_source'=>'data/account/{ids}?fields=kpeiz_post_count_by_type&chart_type=raw&return=summary|sum',
        ],
        'post_count_by_date'=>[
            'uid'=>'post_count_by_date',
            'chart_type'=>'bar',
            'data_source'=>'data/account/{ids}?fields=kpeiz_post_count_by_date',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'post_count_by_hour'=>[
             'uid'=>'post_count_by_hour',
             'chart_type'=>'bar',
             'data_source'=>'data/account/{ids}?fields=kpeiz_post_count_by_hour&chart_type=raw',
             'help' => 'this is to display a help on the widget',
             'options' => []
        ],
        'interactions_by_post_type'=>[
            'uid'=>'interactions_by_post_type',
            'chart_type'=>'pie',
            'data_source'=>'data/account/{ids}?fields=kpeiz_account_interactions_by_post_type&chart_type=raw&return=summary|sum',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        /*'interactions_number'=>[
            'uid'=>'interactions_number',
            'chart_type'=>'line',
            'data_source'=>'data/account/{ids}?fields=kpeiz_account_total_interactions',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],*/
        'interactions_total'=>[
          'uid'=>'interactions_total',
          'chart_type'=>'number',
          'data_source'=>'data/account/{ids}?fields=kpeiz_account_total_interactions&return=summary|sum&chart_type=number',
          'help' => 'this is to display a help on the widget',
          'options' => []
        ],
        'account_engagement_rate'=>[
            'uid'=>'account_engagement_rate',
            'chart_type'=>'number',
            'data_source'=>'data/account/{ids}?fields=kpeiz_account_engagement_rate&return=account|avg',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'average_page_engagement_history' => [
            'uid' => 'average_page_engagement_history',
            'chart_type' => 'line',
            'data_source' => 'data/account/{ids}?fields=kpeiz_account_engagement_rate&chart_type=raw',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'story_count_by_day' => [
            'uid'=>'story_count_by_day',
            'chart_type'=>'bar',
            'data_source'=>'data/account/{ids}?fields=kpeiz_story_count_by_day',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'post_engagement_rate'=>[
            'uid'=>'post_engagement_rate',
            'chart_type'=>'number',
            'data_source'=>'data/account{ids}?fields=kpeiz_post_engagement_rate',
            'help' => 'this is to display a help on the widget',
            'options' => []
        ],
        'stories'=>[
            'uid'=>'stories',
            'chart_type' => 'story',
            'data_source'=>'data/account/{ids}/stories?chart_type=raw',
        ],
    ]

];
                    